Repository strawberry-graphql/strawberry, pull requests merged in 2021-10, with the labels that each got.

#719 Add support for python 3.10
  .devcontainer/post-install.sh
  .github/workflows/release-check.yml
  .github/workflows/test.yml
  RELEASE.md
  poetry.lock
  pyproject.toml
  strawberry/annotation.py
  strawberry/field.py
  strawberry/utils/typing.py
  tests/experimental/pydantic/schema/test_basic.py
  tests/types/resolving/test_unions.py
Labels: bot:has-release-file, bot:release-type-patch

#1287 Add Starlette integration to the documentation
  RELEASE.md
  docs/README.md
  docs/integrations/starlette.md
Labels: ok-to-preview

#1297 Add a test doc page
  docs/_test.md
Labels: ok-to-preview

#1292 Add safety checks (#681)
  RELEASE.md
  strawberry/exceptions.py
  strawberry/object_type.py
  tests/objects/test_types.py
Labels: hacktoberfest-accepted, bot:release-type-minor, bot:has-release-file

#1288 Add Authentication docs
  docs/guides/authentication.md
Labels: hacktoberfest-accepted
